#
# Copyright (c) 2026 Blacknet contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#

[package]
name = "blacknet-snark"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
blacknet-arith.workspace = true
blacknet-crypto.workspace = true
blacknet-vm.workspace = true

[lints]
workspace = true

[lib]
doctest = false
path = "src/main/rust/lib.rs"

[[test]]
name = "proof"
path = "src/test/rust/proof.rs"

[[test]]
name = "fold"
path = "src/test/rust/fold.rs"

[[test]]
name = "committedfold"
path = "src/test/rust/committedfold.rs"

[[test]]
name = "hypernova"
path = "src/test/rust/hypernova.rs"

[[test]]
name = "ivc"
path = "src/test/rust/ivc.rs"

[[test]]
name = "modulecommitment"
path = "src/test/rust/modulecommitment.rs"

[[test]]
name = "pipeline"
path = "src/test/rust/pipeline.rs"
