#
# Copyright (c) 2026 Blacknet contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#

[package]
name = "blacknet-snark"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
blacknet-arith.workspace = true
blacknet-crypto.workspace = true
blacknet-vm.workspace = true

[lints]
workspace = true

[lib]
doctest = false
path = "src/main/rust/lib.rs"

[[test]]
name = "proof"
path = "src/test/rust/proof.rs"

[[test]]
name = "fold"
path = "src/test/rust/fold.rs"

[[test]]
name = "committedfold"
path = "src/test/rust/committedfold.rs"

[[test]]
name = "hypernova"
path = "src/test/rust/hypernova.rs"

[[test]]
name = "ivc"
path = "src/test/rust/ivc.rs"

[[test]]
name = "modulecommitment"
path = "src/test/rust/modulecommitment.rs"

[[test]]
name = "pipeline"
path = "src/test/rust/pipeline.rs"

[[test]]
name = "zk"
path = "src/test/rust/zk.rs"

[[test]]
name = "opening"
path = "src/test/rust/opening.rs"

[[test]]
name = "masking"
path = "src/test/rust/masking.rs"

[[test]]
name = "unifiedcommitment"
path = "src/test/rust/unifiedcommitment.rs"

[[test]]
name = "recursive"
path = "src/test/rust/recursive.rs"

[[test]]
name = "layout_benchmark"
path = "src/test/rust/layout_benchmark.rs"

[[test]]
name = "wire"
path = "src/test/rust/wire.rs"

[[test]]
name = "universal"
path = "src/test/rust/universal.rs"

[[test]]
name = "universal_complete"
path = "src/test/rust/universal_complete.rs"


[[test]]
name = "programbinding"
path = "src/test/rust/programbinding.rs"

[[test]]
name = "universal_run"
path = "src/test/rust/universal_run.rs"


[[test]]
name = "differentiators"
path = "src/test/rust/differentiators.rs"

[[test]]
name = "usecases_zkfi"
path = "src/test/rust/usecases_zkfi.rs"

[[test]]
name = "compose_blacklemon_zkvm"
path = "src/test/rust/compose_blacklemon_zkvm.rs"

[[test]]
name = "programbinding_committed"
path = "src/test/rust/programbinding_committed.rs"

[[test]]
name = "merkle_circuit"
path = "src/test/rust/merkle_circuit.rs"

[[test]]
name = "measurements"
path = "src/test/rust/measurements.rs"

[[test]]
name = "opening_binding"
path = "src/test/rust/opening_binding.rs"
